"""EcoDrone Shared Constants - Public Interface"""

from .limits import (
    # Safety Limits
    MIN_BATTERY_LEVEL,
    MIN_BATTERY_RTH,
    MAX_WIND_SPEED_MPS,
    
    # Physical Limits
    MAX_ALTITUDE_METERS,
    MAX_RANGE_METERS,
    MAX_PAYLOAD_GRAMS,
    
    # Timing
    MISSION_TIMEOUT_SECONDS,
    HEARTBEAT_INTERVAL_SECONDS,
    COMMAND_TIMEOUT_SECONDS,
    
    # Geofencing
    GEOFENCE_BOUNDS,
    
    # States
    DRONE_STATUS_AVAILABLE,
    DRONE_STATUS_IN_MISSION,
    DRONE_STATUS_MAINTENANCE,
    DRONE_STATUS_OFFLINE,
    FLIGHT_STATE_LANDED,
    FLIGHT_STATE_TAKING_OFF,
    FLIGHT_STATE_HOVERING,
    FLIGHT_STATE_FLYING,
    FLIGHT_STATE_LANDING,
    FLIGHT_STATE_EMERGENCY,
)

__all__ = [
    "MIN_BATTERY_LEVEL",
    "MIN_BATTERY_RTH",
    "MAX_WIND_SPEED_MPS",
    "MAX_ALTITUDE_METERS",
    "MAX_RANGE_METERS",
    "MAX_PAYLOAD_GRAMS",
    "MISSION_TIMEOUT_SECONDS",
    "HEARTBEAT_INTERVAL_SECONDS",
    "COMMAND_TIMEOUT_SECONDS",
    "GEOFENCE_BOUNDS",
    "DRONE_STATUS_AVAILABLE",
    "DRONE_STATUS_IN_MISSION",
    "DRONE_STATUS_MAINTENANCE",
    "DRONE_STATUS_OFFLINE",
    "FLIGHT_STATE_LANDED",
    "FLIGHT_STATE_TAKING_OFF",
    "FLIGHT_STATE_HOVERING",
    "FLIGHT_STATE_FLYING",
    "FLIGHT_STATE_LANDING",
    "FLIGHT_STATE_EMERGENCY",
]
